import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const files=fs.readdirSync(path.join(root,'content')).filter(n=>/^lessons-\d\d-\d\d\.json$/.test(n)).sort();
const lessons=files.flatMap(n=>JSON.parse(fs.readFileSync(path.join(root,'content',n),'utf8'))).sort((a,b)=>a.id-b.id);
if(lessons.length!==16||lessons.some((x,i)=>x.id!==i+1))throw Error('Expected lessons 1–16 exactly once');
const common=JSON.parse(fs.readFileSync(path.join(root,'content/common.json'),'utf8'));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad=n=>String(n).padStart(2,'0');
const list=xs=>`<ul>${xs.map(s=>`<li>${esc(s)}</li>`).join('')}</ul>`;
const wrapTables=html=>html.replace(/<table\b/g,'<div class="table-wrap"><table').replace(/<\/table>/g,'</table></div>');
const labels={en:{path:'Bilingual DE / EN',title:'Understanding the polycrisis',subtitle:'Climate, economy and power',overview:'Course',syllabus:'Syllabus',glossary:'Glossary',toolkit:'Toolkit',project:'Project',sources:'Sources',teacher:'Teacher guide',draft:'Initial teaching draft · 6 October 2026',skip:'Skip to content',goals:'Learning goals',agenda:'Your 100-minute lesson',materials:'Materials',support:'Language bridge',submission:'What to hand in',exit:'Exit ticket',homework:'After class · up to 25 minutes',reading:'Source trail',print:'Printable worksheet',prev:'Previous lesson',next:'Next lesson',lesson:'Lesson',course:'16 double lessons · Austrian grades 10–12',notes:'Teacher notes',prepare:'Preparation',facilitate:'Facilitation',answers:'Possible answers and worked examples',misconceptions:'Watch for',differentiation:'Support and stretch',extension:'Extension',terms:'Concepts in two languages',definition:'Explanation',example:'Example',public:'Teacher notes and model answers are openly accessible. They are guidance, not a required political conclusion.',noUpload:'Write on paper or use the assignment platform your teacher names. This website does not collect responses.',initial:'A first complete course draft. Your teacher may adjust timings, sources and assessment before teaching.'},de:{path:'Deutsch mit Englisch-Hilfen',title:'Die Welt im Zusammenhang',subtitle:'Klima, Wirtschaft und Politik',overview:'Kurs',syllabus:'Kursplan',glossary:'Glossar',toolkit:'Werkzeuge',project:'Projekt',sources:'Quellen',teacher:'Hinweise für Lehrkräfte',draft:'Erster Unterrichtsentwurf · 6. Oktober 2026',skip:'Zum Inhalt springen',goals:'Lernziele',agenda:'Deine Doppelstunde: 100 Minuten',materials:'Materialien',support:'Sprachbrücke',submission:'Das gibst du ab',exit:'Abschlussfragen',homework:'Nach der Stunde · höchstens 25 Minuten',reading:'Quellen zum Nachprüfen',print:'Druckbares Arbeitsblatt',prev:'Vorherige Stunde',next:'Nächste Stunde',lesson:'Stunde',course:'16 Doppelstunden · 10.–12. Schulstufe in Österreich',notes:'Hinweise für Lehrkräfte',prepare:'Vorbereitung',facilitate:'Durchführung',answers:'Mögliche Antworten und Rechenwege',misconceptions:'Darauf achten',differentiation:'Unterstützung und Vertiefung',extension:'Vertiefung',terms:'Begriffe in zwei Sprachen',definition:'Erklärung',example:'Beispiel',public:'Hinweise und Antwortvorschläge sind öffentlich zugänglich. Sie schreiben keine politische Schlussfolgerung vor.',noUpload:'Arbeite auf Papier oder nutze die von deiner Lehrkraft genannte Aufgabenplattform. Diese Website sammelt keine Antworten.',initial:'Ein erster vollständiger Kursentwurf. Deine Lehrkraft kann Zeitplan, Quellen und Beurteilung vor dem Unterricht anpassen.'}};
function page(lang,title,body,{file='index.html',hero='',worksheet=false}={}){
 const l=labels[lang],other=lang==='en'?'de':'en';
 const navigation=[['index.html','overview'],['syllabus.html','syllabus'],['glossary.html','glossary'],['toolkit.html','toolkit'],['project.html','project'],['sources.html','sources'],['teacher.html','teacher']];
 return `<!doctype html>\n<html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${esc(l.course+' — '+title)}"><title>${esc(title)} · Polycrisis · GRG23</title><link rel="stylesheet" href="../assets/course.css"></head><body${worksheet?' class="worksheet"':''}><a class="skip" href="#main">${l.skip}</a><div class="shell"><div class="topline"><strong>pnorthup.me/grg23 → polycrisis</strong><a href="../${other}/${file}" lang="${other}">${other==='de'?'Deutsch mit Englisch-Hilfen':'Bilingual DE / EN'}</a></div>${hero?`<header class="hero">${hero}</header>`:''}<nav class="nav" aria-label="${lang==='en'?'Course navigation':'Kursnavigation'}">${navigation.map(([href,key])=>`<a href="${href}"${file===href?' aria-current="page"':''}>${l[key]}</a>`).join('')}</nav><main id="main">${body}</main><footer class="footer"><p>${l.draft} · ${l.path}. <a href="../index.html">${lang==='en'?'Choose a pathway':'Kursweg wählen'}</a></p><p>${l.noUpload}</p></footer></div></body></html>\n`;
}
function write(lang,file,text){fs.mkdirSync(path.join(root,lang),{recursive:true});fs.writeFileSync(path.join(root,lang,file),text);}
const hero=(lang,title,description,eyebrow)=>`<span class="eyebrow">${esc(eyebrow||labels[lang].path)}</span><h1>${esc(title)}</h1><p>${esc(description)}</p><span class="tag">${labels[lang].course}</span>`;
const materialHTML=(d)=>d.materials.map((m,i)=>`<article id="material-${i+1}"><h3 class="material-title">${esc(m.title)}</h3>${wrapTables(m.html)}</article>`).join('');
const sourceHTML=(d)=>`<ol class="sources">${d.sources.map(s=>`<li><a href="${esc(s.url)}">${esc(s.title)}</a><small>${esc(s.date)} · ${esc(s.use)}</small></li>`).join('')}</ol>`;
for(const lang of ['en','de']){
 const l=labels[lang],c=common[lang];
 const cards=lessons.map(x=>`<article class="card"><span class="number">${l.lesson} ${pad(x.id)}</span><h2><a href="lesson-${pad(x.id)}.html">${esc(x[lang].title)}</a></h2><p>${esc(x[lang].question)}</p></article>`).join('');
 const lead=lang==='en'?'<p>Follow the connections. Test the evidence. Ask who has the power to act.</p><p>Three investigations: Europe’s energy shock; Sri Lanka’s 2022 crisis; the politics of the energy transition. We also ask when “polycrisis” is a useful explanation.</p>':'<p>Verbindungen erklären. Belege prüfen. Fragen, wer handeln kann.</p><p>Drei Untersuchungen: Europas Energiepreisschock, Sri Lankas Krise 2022 und die Politik der Energiewende. Wir prüfen auch, wann „Polykrise“ eine hilfreiche Erklärung ist.</p>';
 const language=lang==='en'?'English is the main working language. German sources connect international arguments to Austria. Use the German pathway for additional explanations.':'Erklärungen, Diskussionen und Abgaben sind auf Deutsch. Kurze englische Sprachbrücken helfen beim Zugang zu internationalen Quellen. Die fachlichen Ziele sind dieselben wie im bilingualen Kurs.';
 write(lang,'index.html',page(lang,l.title,`<section class="panel">${lead}<div class="callout">${language}</div><p class="meta">${l.initial}</p><a class="button" href="lesson-01.html">${lang==='en'?'Start lesson 01':'Mit Stunde 01 beginnen'}</a> <a class="button" href="syllabus.html">${l.syllabus}</a></section><section aria-label="${lang==='en'?'Lessons':'Doppelstunden'}" class="grid">${cards}</section>`,{hero:hero(lang,l.title,l.subtitle)}));
 const overview=`<div class="table-wrap"><table><caption>${lang==='en'?'Semester sequence':'Ablauf des Semesters'}</caption><thead><tr><th>${l.lesson}</th><th>${lang==='en'?'Investigation':'Untersuchung'}</th><th>${lang==='en'?'Question':'Leitfrage'}</th></tr></thead><tbody>${lessons.map(x=>`<tr><td>${pad(x.id)}</td><td><a href="lesson-${pad(x.id)}.html">${esc(x[lang].title)}</a></td><td>${esc(x[lang].question)}</td></tr>`).join('')}</tbody></table></div>`;
 write(lang,'syllabus.html',page(lang,l.syllabus,`<section class="panel reading">${c.syllabusHtml}</section><section class="panel">${overview}</section>`,{file:'syllabus.html',hero:hero(lang,l.syllabus,l.course)}));
 for(const [name,key] of [['toolkit','toolkitHtml'],['project','projectHtml']])write(lang,`${name}.html`,page(lang,l[name],`<section class="panel">${wrapTables(c[key])}</section>`,{file:`${name}.html`,hero:hero(lang,l[name],lang==='en'?'Use, print and adapt these shared materials.':'Diese Materialien kannst du nutzen, drucken und anpassen.')}));
 write(lang,'glossary.html',page(lang,l.glossary,`<section class="panel"><div class="table-wrap"><table><caption>${l.terms}</caption><thead><tr><th>English</th><th>Deutsch</th><th>${l.definition}</th><th>${l.example}</th></tr></thead><tbody>${c.glossary.map(g=>`<tr><th scope="row">${esc(g.en)}</th><td>${esc(g.de)}</td><td>${esc(g.definition)}</td><td>${esc(g.example)}</td></tr>`).join('')}</tbody></table></div><p class="meta">${lang==='en'?'Teacher-written working definitions. Historical claims and numerical evidence need the source trail in each lesson.':'Von der Lehrkraft verfasste Arbeitsdefinitionen. Historische Aussagen und Zahlen müssen mit den Quellen der jeweiligen Stunde geprüft werden.'}</p></section>`,{file:'glossary.html',hero:hero(lang,l.glossary,l.terms)}));
 write(lang,'sources.html',page(lang,l.sources,`<section class="panel"><p>${lang==='en'?'Read historical sources in their original context. A source’s publication date is not the date of every fact it reports. Classroom readers are original educational summaries, not quotations or endorsed author texts. Hypothetical numbers teach a mechanism; they do not measure a country.':'Lies historische Quellen in ihrem damaligen Zusammenhang. Das Veröffentlichungsdatum ist nicht automatisch das Datum aller genannten Fakten. Die Lesetexte sind eigene Unterrichtszusammenfassungen, keine Zitate oder von den Autorinnen und Autoren geprüfte Texte. Erfundenes Zahlenmaterial erklärt einen Mechanismus; es beschreibt kein Land.'}</p><p>${lang==='en'?'For every source record: author or institution, publication date, claim, evidence, perspective, limitation and URL. Use the source log in the toolkit.':'Notiere bei jeder Quelle: Autor oder Institution, Datum, Aussage, Belege, Perspektive, Grenze und URL. Nutze das Quellenprotokoll unter Werkzeuge.'}</p></section>${lessons.map(x=>`<section class="panel" id="lesson-${pad(x.id)}"><h2><a href="lesson-${pad(x.id)}.html">${pad(x.id)} · ${esc(x[lang].title)}</a></h2>${sourceHTML(x[lang])}</section>`).join('')}`,{file:'sources.html',hero:hero(lang,l.sources,lang==='en'?'Authors, evidence and reading routes':'Autorinnen und Autoren, Belege und Lesewege')}));
 const notes=lessons.map(x=>{const t=x[lang].teacher;return `<section class="panel" id="lesson-${pad(x.id)}"><h2>${pad(x.id)} · ${esc(x[lang].title)}</h2><p><a href="lesson-${pad(x.id)}.html">${lang==='en'?'Student lesson':'Zur Unterrichtsseite'}</a> · <a href="lesson-${pad(x.id)}-worksheet.html">${l.print}</a></p>${[['preparation','prepare'],['facilitation','facilitate'],['answers','answers'],['misconceptions','misconceptions'],['differentiation','differentiation']].map(([key,label])=>`<h3>${l[label]}</h3>${list(t[key])}`).join('')}<h3>${l.extension}</h3><p>${esc(t.extension)}</p></section>`;}).join('');
 write(lang,'teacher.html',page(lang,l.teacher,`<section class="panel"><div class="callout warning">${l.public}</div>${c.teacherIntroHtml}<p>${lessons.map(x=>`<a href="#lesson-${pad(x.id)}">${pad(x.id)}</a>`).join(' · ')}</p></section>${notes}`,{file:'teacher.html',hero:hero(lang,l.teacher,lang==='en'?'Preparation, model reasoning and classroom decisions':'Vorbereitung, Antwortvorschläge und Unterrichtsentscheidungen')}));
 for(const lesson of lessons){
  const d=lesson[lang],file=`lesson-${pad(lesson.id)}.html`;
  if(d.agenda.reduce((n,a)=>n+a.minutes,0)!==100)throw Error(`${lang} lesson ${lesson.id}: timing is not 100`);
  const toc=`<aside class="toc"><strong>${l.lesson} ${pad(lesson.id)}</strong><ol>${['goals','agenda','materials','support','submission','exit','reading'].map(key=>`<li><a href="#${key}">${l[key]}</a></li>`).join('')}</ol><p><a href="lesson-${pad(lesson.id)}-worksheet.html">${l.print}</a></p><p><a href="teacher.html#lesson-${pad(lesson.id)}">${l.notes}</a></p></aside>`;
  const body=`<div class="lesson-layout">${toc}<div><section class="panel" id="goals"><h2>${l.goals}</h2><p>${esc(d.intro)}</p>${list(d.goals)}</section><section class="panel" id="agenda"><h2>${l.agenda}</h2><ol class="agenda">${d.agenda.map(a=>`<li><span class="minutes">${a.minutes} min</span><div><h3>${esc(a.title)}</h3><p>${esc(a.task)}</p></div></li>`).join('')}</ol></section><section class="panel materials" id="materials"><h2>${l.materials}</h2>${materialHTML(d)}</section><section class="panel" id="support"><h2>${l.support}</h2>${d.languageSupport}</section><section class="panel" id="submission"><h2>${l.submission}</h2><p>${esc(d.submission)}</p><p class="meta">${l.noUpload}</p></section><section class="panel" id="exit"><h2>${l.exit}</h2>${list(d.exit)}<h3>${l.homework}</h3><p>${esc(d.homework)}</p></section><section class="panel" id="reading"><h2>${l.reading}</h2>${sourceHTML(d)}</section><div class="pager">${lesson.id>1?`<a href="lesson-${pad(lesson.id-1)}.html">← ${l.prev}</a>`:'<span></span>'}${lesson.id<16?`<a href="lesson-${pad(lesson.id+1)}.html">${l.next} →</a>`:`<a href="project.html">${l.project}</a>`}</div></div></div>`;
  write(lang,file,page(lang,d.title,body,{file,hero:hero(lang,d.title,d.question,`${l.lesson} ${pad(lesson.id)} · ${l.path}`)}));
  const wsfile=`lesson-${pad(lesson.id)}-worksheet.html`;
  write(lang,wsfile,page(lang,d.title,`<header><p class="eyebrow">${l.lesson} ${pad(lesson.id)} · ${l.print}</p><h1>${esc(d.title)}</h1><p>${esc(d.question)}</p><p>${lang==='en'?'Name / group: __________________________ Date: ______________':'Name / Gruppe: __________________________ Datum: ______________'}</p><p class="no-print">${lang==='en'?'Use your browser’s Print command. This page includes the assignment steps, materials and response space.':'Nutze den Druckbefehl deines Browsers. Diese Seite enthält Arbeitsschritte, Materialien und Platz für Antworten.'} <a href="${file}">${lang==='en'?'Return to lesson':'Zurück zur Stunde'}</a></p></header><section class="panel"><h2>${l.agenda}</h2><ol>${d.agenda.map(a=>`<li><strong>${a.minutes} min · ${esc(a.title)}</strong><p>${esc(a.task)}</p></li>`).join('')}</ol></section><section class="panel materials"><h2>${l.materials}</h2>${materialHTML(d)}</section><section class="panel"><h2>${l.support}</h2>${d.languageSupport}</section><section class="panel"><h2>${l.submission}</h2><p>${esc(d.submission)}</p><div class="response-space"></div><div class="response-space"></div><h2>${l.exit}</h2>${d.exit.map(s=>`<p>${esc(s)}</p><div class="response-space"></div>`).join('')}<h3>${l.homework}</h3><p>${esc(d.homework)}</p></section><section class="panel"><h2>${l.reading}</h2>${sourceHTML(d)}</section>`,{file:wsfile,worksheet:true}));
 }
}
fs.writeFileSync(path.join(root,'index.html'),`<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="A semester elective on climate, economy and power for Austrian grades 10–12, with bilingual and German-led pathways."><title>Polycrisis · Climate, economy and power · GRG23</title><link rel="stylesheet" href="assets/course.css"></head><body><a class="skip" href="#main">Skip to content / Zum Inhalt</a><div class="shell"><div class="topline"><strong>pnorthup.me/grg23 → polycrisis</strong><span>GRG23 · Semester elective</span></div><header class="hero"><span class="eyebrow">16 double lessons · Grades 10–12</span><h1>One world.<br>Connected crises.<br>Political choices.</h1><p>Explore climate, economy and power through Adam Tooze, The Polycrisis and Phenomenal World—and test their arguments against evidence.</p><span class="tag">100 minutes per lesson</span><span class="tag">Two language pathways</span></header><main id="main"><section class="grid" aria-label="Choose a course pathway"><article class="card path-card"><span class="number">Bilingual DE / EN</span><h2><a href="en/">Understanding the polycrisis</a></h2><p>English-led lessons, German connections to Austria, supported original-source reading, and English analytical work.</p><a class="button" href="en/">Open bilingual course →</a></article><article class="card path-card" lang="de"><span class="number">Deutsch mit Englisch-Hilfen</span><h2><a href="de/">Die Welt im Zusammenhang</a></h2><p>Unterricht und Abgaben auf Deutsch. Kurze englische Sprachbrücken öffnen den Zugang zu internationalen Quellen. Gleiche fachliche Ziele.</p><a class="button" href="de/">Deutschen Kurs öffnen →</a></article></section><section class="panel"><h2>Follow connections. Explain mechanisms. Judge choices.</h2><p>Start with Europe’s energy shock, investigate Sri Lanka’s 2022 crisis, and examine the politics of the energy transition. Ask who is exposed, who can act, and when the idea of a polycrisis helps us understand.</p><p>Each lesson includes a timed assignment sequence, local readers and activity materials, a printable worksheet, language support, a source trail and public teacher guidance.</p><p class="meta">Initial teaching draft · 6 October 2026. Historical cases are dated. Hypothetical classroom data are labelled. Assessment arrangements are chosen by the teacher.</p></section></main><footer class="footer"><p>This course is publicly accessible by its direct address. Student responses are completed on paper or the teacher’s assignment platform.</p></footer></div></body></html>\n`);
console.log(`Built ${lessons.length} lessons × 2 pathways, worksheets and shared course pages.`);
